In [1]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
import pandas as pd
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# Load dataset
df = pd.read_csv('text.csv')
#df = df.sample(frac=0.5)


In [3]:
df.tail(10)

Unnamed: 0                                               text  label
416799      416799  i feel that i must confess even though it kill...      5
416800      416800  i don t know why today i feel like it looks ve...      1
416801      416801  i don t even feel like i fully resolved it but...      1
416802      416802  i feel like i have been neglecting you my fait...      1
416803      416803  i cry and feel a sense of loss when my patient...      1
416804      416804  i feel like telling these horny devils to find...      2
416805      416805  i began to realize that when i was feeling agi...      3
416806      416806  i feel very curious be why previous early dawn...      5
416807      416807  i feel that becuase of the tyranical nature of...      3
416808      416808  i think that after i had spent some time inves...      5

In [4]:
y1 = df['label']
y1.value_counts()

label
1    141067
0    121187
3     57317
4     47712
2     34554
5     14972
Name: count, dtype: int64

In [5]:
# Define the mapping between emotion labels and sentiment labels
emotion_to_sentiment = {
    0: 0,  # sadness
    1: 1,  # joy
    2: 1,  # love
    3: 0,  # anger
    4: 2,   # fear
    5: 2    # surprise
}

# Map emotion labels to sentiment labels and create a new column 'sentiment'
df['sentiment'] = df['label'].map(emotion_to_sentiment)

# Print the first few rows to check the result
print(df.head())


   Unnamed: 0                                               text  label  \
0           0      i just feel really helpless and heavy hearted      4   
1           1  ive enjoyed being able to slouch about relax a...      0   
2           2  i gave up my internship with the dmrg and am f...      4   
3           3                         i dont know i feel so lost      0   
4           4  i am a kindergarten teacher and i am thoroughl...      4   

   sentiment  
0          2  
1          0  
2          2  
3          0  
4          2  


In [6]:
print(df.head(50))

    Unnamed: 0                                               text  label  \
0            0      i just feel really helpless and heavy hearted      4   
1            1  ive enjoyed being able to slouch about relax a...      0   
2            2  i gave up my internship with the dmrg and am f...      4   
3            3                         i dont know i feel so lost      0   
4            4  i am a kindergarten teacher and i am thoroughl...      4   
5            5         i was beginning to feel quite disheartened      0   
6            6  i would think that whomever would be lucky eno...      2   
7            7  i fear that they won t ever feel that deliciou...      1   
8            8  im forever taking some time out to have a lie ...      5   
9            9  i can still lose the weight without feeling de...      0   
10          10  i try to be nice though so if you get a bitchy...      1   
11          11  im feeling a little like a damaged tree and th...      0   
12          

In [7]:
df = df.dropna()
X = df.drop('sentiment', axis=1)
y = df['sentiment']

In [8]:
y.value_counts()

sentiment
0    178504
1    175621
2     62684
Name: count, dtype: int64

In [9]:
X.shape

(416809, 3)

In [10]:
y.shape

(416809,)

In [11]:
import tensorflow as tf
tf.__version__


'2.14.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [13]:
voc_size = 50000
texts = X.copy()

In [14]:
texts['text'][1]

'ive enjoyed being able to slouch about relax and unwind and frankly needed it after those last few weeks around the end of uni and the expo i have lately started to find myself feeling a bit listless which is never really a good thing'

In [15]:
texts.reset_index(inplace=True)
import nltk
import re
from nltk.corpus import stopwords

In [16]:
custom_stopwords = [
    "i","im","like", "feel", "feeling", "my", "the", "to",
                     "for","know","littl","think","time","thing","would","go",
                     "realli","feel","am","so","get", "one", "to", "and", "at", "can",
                     "day","way", "make", "me", "want", "could" , "would", "tri", "u"                      
                     ]


all_stopwords=stopwords.words('english') + custom_stopwords

print(all_stopwords)


import re
import preprocessor as p
from nltk.stem import PorterStemmer


#  function to clean text data
def preprocessing(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\W', ' ', text)  # Remove all non-word characters
    text = re.sub(r'\s+', ' ', text)  # Replace all runs of whitespaces with a single space
    # Optionally, remove stopwords and stem
    words = text.split()
    words = [word for word in words if word not in all_stopwords]
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    return ' '.join(words)



['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [17]:
new_data = df["text"].apply(preprocessing)

new_data = pd.DataFrame(new_data)

new_data.head()

text
0                        realli helpless heavi heart
1  ive enjoy abl slouch relax unwind frankli need...
2                    gave internship dmrg distraught
3                                          dont lost
4  kindergarten teacher thoroughli weari job take...

In [18]:
new_data

text
0                             realli helpless heavi heart
1       ive enjoy abl slouch relax unwind frankli need...
2                         gave internship dmrg distraught
3                                               dont lost
4       kindergarten teacher thoroughli weari job take...
...                                                   ...
416804  tell horni devil find site suit sort interest ...
416805            began realiz agit restless thought dish
416806              curiou previou earli dawn seek troubl
416807  becuas tyran natur govern el salvador savag so...
416808   spent investig surround thing start curiou peopl

[416809 rows x 1 columns]

In [19]:
import numpy as np

# Assuming df is your DataFrame containing the text data
array_data = new_data['text'].values

print(array_data)


['realli helpless heavi heart'
 'ive enjoy abl slouch relax unwind frankli need last week around end uni expo late start find bit listless never realli good'
 'gave internship dmrg distraught' ...
 'curiou previou earli dawn seek troubl'
 'becuas tyran natur govern el salvador savag social condit gener peopl set thought run shoe shop miguel marmol testimoney abl work'
 'spent investig surround thing start curiou peopl']


In [20]:
onehot_repr=[one_hot(words,voc_size)for words in array_data] 
onehot_repr

[[17323, 9731, 14630, 35277],
 [25778,
  10497,
  3279,
  3296,
  26613,
  5434,
  36289,
  9933,
  17639,
  22202,
  818,
  6972,
  30218,
  49477,
  38646,
  25049,
  15638,
  123,
  46765,
  45134,
  17323,
  3605],
 [6978, 22064, 1379, 29699],
 [41730, 36435],
 [8300,
  23558,
  19889,
  40428,
  19319,
  46951,
  9843,
  32496,
  26887,
  27756,
  33585,
  22202,
  25188,
  27346,
  39645,
  24594],
 [25933, 2673, 10382],
 [31794, 4262, 29054, 11318, 28917, 18740, 19930, 19881, 18068],
 [34539, 3449, 44050, 28153, 47757, 16304, 18601, 518],
 [34603, 30668, 10990, 22897],
 [28711, 21412, 9447, 6588, 8622],
 [3249,
  48278,
  26832,
  26227,
  16052,
  15081,
  13141,
  43048,
  22629,
  34208,
  99,
  19645,
  4792],
 [22629, 30897, 37797, 32682, 22629, 41592],
 [22836, 37505, 9581, 3050],
 [2962,
  42326,
  49398,
  20432,
  28556,
  33328,
  10893,
  10216,
  31556,
  24125,
  33328,
  47644,
  27769,
  44171,
  49398,
  44909,
  39934,
  6252,
  34966,
  15149],
 [976, 1649, 298

# Embedding Representation

In [21]:
sent_length=20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0 ...  9731 14630 35277]
 [ 3279  3296 26613 ... 45134 17323  3605]
 [    0     0     0 ... 22064  1379 29699]
 ...
 [    0     0     0 ... 24652 21990 19785]
 [ 3371 41519  3054 ... 26212  3279 27346]
 [    0     0     0 ... 25049  9889 28851]]


In [22]:
embedded_docs[0]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0, 17323,  9731,
       14630, 35277])

In [23]:
## Creating model
embedding_vector_features=10
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(50))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 10)            500000    
                                                                 
 lstm (LSTM)                 (None, 50)                12200     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 512251 (1.95 MB)
Trainable params: 512251 (1.95 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [24]:
## Creating model
embedding_vector_features=10
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(50)))
model1.add(Dropout(0.1))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 10)            500000    
                                                                 
 bidirectional (Bidirection  (None, 100)               24400     
 al)                                                             
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 524501 (2.00 MB)
Trainable params: 524501 (2.00 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [25]:
len(embedded_docs),y.shape

(416809, (416809,))

In [26]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [27]:
X_final.shape,y_final.shape

((416809, 20), (416809,))

# Splitting the Dataset

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.1, random_state = 42)

# Training the model

In [29]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10)

Epoch 1/10
11723/11723 [==============================] - 218s 18ms/step - loss: -58.9121 - accuracy: 0.7482 - val_loss: -124.0675 - val_accuracy: 0.7656
Epoch 2/10
11723/11723 [==============================] - 202s 17ms/step - loss: -173.8807 - accuracy: 0.7563 - val_loss: -241.3604 - val_accuracy: 0.7683
Epoch 3/10
11723/11723 [==============================] - 211s 18ms/step - loss: -287.1262 - accuracy: 0.7458 - val_loss: -357.9121 - val_accuracy: 0.7605
Epoch 4/10
11723/11723 [==============================] - 205s 17ms/step - loss: -418.5685 - accuracy: 0.7484 - val_loss: -488.8262 - val_accuracy: 0.7621
Epoch 5/10
11723/11723 [==============================] - 204s 17ms/step - loss: -545.0220 - accuracy: 0.7495 - val_loss: -619.4438 - val_accuracy: 0.7680
Epoch 6/10
11723/11723 [==============================] - 224s 19ms/step - loss: -664.4774 - accuracy: 0.7563 - val_loss: -747.9258 - val_accuracy: 0.7733
Epoch 7/10
11723/11723 [==============================] - 214s 18ms/ste

In [41]:
X_test

array([[    0,     0,     0, ..., 29033, 49813, 15442],
       [    0,     0,     0, ...,  3955, 38494,  8771],
       [    0,     0,     0, ..., 31115, 43503, 15652],
       ...,
       [    0,     0,     0, ...,   415, 11235, 13088],
       [    0,     0,     0, ...,   123,  7172, 42781],
       [    0,     0,     0, ..., 40830, 40936, 27346]])

In [30]:
y_pred1 = model1.predict(X_test)
y_pred_classes = (y_pred1 > 0.5).astype("int64")

1303/1303 [==============================] - 8s 6ms/step


In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_classes)

array([[16185,  1494,     0],
       [ 1107, 16530,     0],
       [  181,  6184,     0]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_classes)

0.7848899978407428

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_classes))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92     17679
           1       0.68      0.94      0.79     17637
           2       0.00      0.00      0.00      6365

    accuracy                           0.78     41681
   macro avg       0.54      0.62      0.57     41681
weighted avg       0.68      0.78      0.72     41681



C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
model1.save("BI_LSTM")

INFO:tensorflow:Assets written to: BI_LSTM\assets


INFO:tensorflow:Assets written to: BI_LSTM\assets


In [23]:
from tensorflow.keras.models import load_model

# Load the saved model
model_l = load_model("BI_LSTM")

In [39]:
import pandas as pd
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
# Feature Scaling
from sklearn.preprocessing import StandardScaler
df1 = pd.read_csv('test_sample.csv')

In [40]:
custom_stopwords = [
    "i","im","like", "feel", "feeling", "my", "the", "to",
                     "for","know","littl","think","time","thing","would","go",
                     "realli","feel","am","so","get", "one", "to", "and", "at", "can",
                     "day","way", "make", "me", "want", "could" , "would", "tri", "u"                      
                     ]


all_stopwords=stopwords.words('english') + custom_stopwords

print(all_stopwords)


import re
import preprocessor as p
from nltk.stem import PorterStemmer


#  function to clean text data
def preprocessing(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\W', ' ', text)  # Remove all non-word characters
    text = re.sub(r'\s+', ' ', text)  # Replace all runs of whitespaces with a single space
    # Optionally, remove stopwords and stem
    words = text.split()
    words = [word for word in words if word not in all_stopwords]
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    return ' '.join(words)



['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [41]:
new_data = df1["text"].apply(preprocessing)

new_data = pd.DataFrame(new_data)

new_data.head()

text
0  realli wanna stay hous tonight creepi
1                            scare snake
2                                   love
3                                   ever
4                             templ side

In [42]:
new_data

text
0                 realli wanna stay hous tonight creepi
1                                           scare snake
2                                                  love
3                                                  ever
4                                            templ side
...                                                 ...
1996  alreadi differ strength techniqu class three c...
1997                           low havent felt low suck
1998                absolut 1 skinni fiber wonder fabul
1999                               strang cathol vortex
2000  mani 2d learn nearli year say goodby guid ente...

[2001 rows x 1 columns]

In [43]:
sample = new_data['text'].values

print(sample)

['realli wanna stay hous tonight creepi' 'scare snake' 'love' ...
 'absolut 1 skinni fiber wonder fabul' 'strang cathol vortex'
 'mani 2d learn nearli year say goodby guid entertain']


In [44]:
voc_size = 50000

onehot_repr=[one_hot(words,voc_size)for words in sample] 
onehot_repr

[[37638, 35839, 27493, 39586, 39364, 49422],
 [7075, 13012],
 [11198],
 [12701],
 [9979, 28642],
 [22959, 39477, 48523, 11772],
 [44443, 45124, 29477],
 [8486, 25801, 35496],
 [24325, 22874, 16396, 39923],
 [34590, 41711, 6563, 17519],
 [14911,
  15087,
  37817,
  9994,
  21074,
  9212,
  18658,
  3817,
  37638,
  24320,
  12553,
  38673,
  28584],
 [37701, 11636, 1440, 7875, 47013],
 [13566, 30479, 49290, 15428, 26332],
 [554, 9212, 44194, 22957, 25379, 34365, 38275, 21891, 33467, 33412, 31744],
 [11172, 42063, 27102, 37321, 45603],
 [32018, 47578, 37286, 11198, 33892, 30301],
 [21140, 32609],
 [37638, 35839, 27493, 39586, 39364, 49422],
 [18826,
  48113,
  11524,
  37770,
  7875,
  47053,
  41948,
  34226,
  15823,
  36444,
  6649,
  15823,
  41574,
  5039,
  22504,
  29020,
  33470,
  8185],
 [11198],
 [11913],
 [13078, 41574],
 [7075, 13012],
 [],
 [27607, 32810, 41574],
 [6335, 15340],
 [20461, 46427, 6971],
 [45385, 4480, 39578],
 [21140, 9212, 33470],
 [31975, 48705, 37286],
 [3

In [45]:
sent_length=20
data = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(data)

[[    0     0     0 ... 39586 39364 49422]
 [    0     0     0 ...     0  7075 13012]
 [    0     0     0 ...     0     0 11198]
 ...
 [    0     0     0 ... 28376 38125 49120]
 [    0     0     0 ... 12038 30414 17780]
 [    0     0     0 ... 27142 43811 43800]]


In [46]:
data

array([[    0,     0,     0, ..., 39586, 39364, 49422],
       [    0,     0,     0, ...,     0,  7075, 13012],
       [    0,     0,     0, ...,     0,     0, 11198],
       ...,
       [    0,     0,     0, ..., 28376, 38125, 49120],
       [    0,     0,     0, ..., 12038, 30414, 17780],
       [    0,     0,     0, ..., 27142, 43811, 43800]])

In [47]:
predicted = model_l.predict(data)

63/63 [==============================] - 0s 3ms/step


In [48]:
predicted
output = (predicted > 0.5).astype("int64")

In [49]:
output

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [50]:
expected = df1['label']

In [51]:
expected

0       0
1       1
2       1
3       0
4       1
       ..
1996    2
1997    0
1998    1
1999    2
2000    2
Name: label, Length: 2001, dtype: int64

In [52]:
from sklearn.metrics import accuracy_score

accuracy_score(expected,output)

0.42528735632183906