In [1]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\patil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
import pandas as pd
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# Load dataset
df = pd.read_csv('test_project.csv')
#df = df.sample(frac=0.5)


In [3]:
df.tail(10)

Text  Emotion
21449  Edouard looked at him , and felt a sickening dism        2
21450  When Tina and the children moved into the Scho...        2
21451  But he felt ` dismay and sorrow for so many pe...        2
21452  They stared at one another in dismay , the sad...        2
21453              Cleo stared at the contents with dism        2
21454               Melissa stared at her friend in dism        2
21455  Successive state elections have seen the gover...        2
21456               Vincent was irritated but not dismay        2
21457  Kendall-Hume turned back to face the dismayed ...        2
21458                    I am dismayed , but not surpris        2

In [4]:
y1 = df['Emotion']
y1.value_counts()

Emotion
0    9258
1    8670
2    3531
Name: count, dtype: int64

In [5]:
print(df.head(50))

                                                 Text  Emotion
0                             i didnt feel humiliated        0
1   i can go from feeling so hopeless to so damned...        0
2    im grabbing a minute to post i feel greedy wrong        0
3   i am ever feeling nostalgic about the fireplac...        1
4                                i am feeling grouchy        0
5   ive been feeling a little burdened lately wasn...        0
6   ive been taking or milligrams or times recomme...        2
7   i feel as confused about life as a teenager or...        2
8   i have been with petronas for years i feel tha...        1
9                                 i feel romantic too        1
10  i feel like i have to make the suffering i m s...        0
11  i do feel that running is a divine experience ...        1
12  i think it s the easiest time of year to feel ...        0
13                 i feel low energy i m just thirsty        0
14  i have immense sympathy with the general point...  

In [6]:
df = df.dropna()
X = df.drop('Emotion', axis=1)
y = df['Emotion']

In [7]:
y.value_counts()

Emotion
0    9258
1    8670
2    3531
Name: count, dtype: int64

In [8]:
X.shape

(21459, 1)

In [9]:
y.shape

(21459,)

In [10]:
import tensorflow as tf
tf.__version__


'2.14.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size = 5000
texts = X.copy()

In [13]:
texts['Text'][1]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [14]:
texts.reset_index(inplace=True)
import nltk
import re
from nltk.corpus import stopwords

In [15]:
custom_stopwords = [
    "i","im","like", "feel", "feeling", "my", "the", "to",
                     "for","know","littl","think","time","thing","would","go",
                     "realli","feel","am","so","get", "one", "to", "and", "at", "can",
                     "day","way", "make", "me", "want", "could" , "would", "tri", "u"                      
                     ]


all_stopwords=stopwords.words('english') + custom_stopwords

print(all_stopwords)


import re
import preprocessor as p
from nltk.stem import PorterStemmer


#  function to clean text data
def preprocessing(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\W', ' ', text)  # Remove all non-word characters
    text = re.sub(r'\s+', ' ', text)  # Replace all runs of whitespaces with a single space
    # Optionally, remove stopwords and stem
    words = text.split()
    words = [word for word in words if word not in all_stopwords]
    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]
    return ' '.join(words)



['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [16]:
new_data = df["Text"].apply(preprocessing)

new_data = pd.DataFrame(new_data)

new_data.head()

Text
0                                didnt humili
1  hopeless damn hope around someon care awak
2                grab minut post greedi wrong
3        ever nostalg fireplac still properti
4                                     grouchi

In [17]:
new_data

Text
0                                           didnt humili
1             hopeless damn hope around someon care awak
2                           grab minut post greedi wrong
3                   ever nostalg fireplac still properti
4                                                grouchi
...                                                  ...
21454                          melissa stare friend dism
21455  success state elect seen govern parti pummel d...
21456                               vincent irrit dismay
21457             kendal hume turn back face dismay coup
21458                                      dismay surpri

[21459 rows x 1 columns]

In [18]:
import numpy as np

# Assuming df is your DataFrame containing the text data
array_data = new_data['Text'].values

print(array_data)


['didnt humili' 'hopeless damn hope around someon care awak'
 'grab minut post greedi wrong' ... 'vincent irrit dismay'
 'kendal hume turn back face dismay coup' 'dismay surpri']


In [19]:
onehot_repr=[one_hot(words,voc_size)for words in array_data] 
onehot_repr

[[4924, 2913],
 [4729, 478, 1507, 1960, 4488, 1603, 4180],
 [2251, 4903, 3872, 661, 1683],
 [3563, 875, 610, 2822, 2227],
 [461],
 [4828, 2091, 4335, 3713, 1616, 783],
 [4828, 1016, 1688, 1820, 4550, 1949, 4828, 247, 4064, 4394, 2687, 248, 2182],
 [2906, 980, 1191, 2529, 1193, 211, 1839],
 [2654, 1193, 2654, 1926, 1820, 3072, 2509, 2601],
 [1833],
 [3112, 747, 2930, 824],
 [695, 2550, 2887, 3400, 1514, 3586, 2050],
 [380, 1193, 1213],
 [1597, 4998, 4921],
 [2784,
  1715,
  636,
  4200,
  4353,
  3644,
  908,
  2850,
  1213,
  691,
  1355,
  980,
  2124,
  4937,
  3153,
  1464,
  1352,
  4023,
  1202,
  2091,
  686],
 [1133, 2733, 785],
 [4924, 3648, 2777],
 [1370, 2873],
 [2056, 1413, 652, 1797, 1559, 2905, 4424, 356, 652, 2996],
 [3824, 4501, 3037, 4726, 1997, 2512, 2433],
 [2852, 1371, 2495, 4261, 295, 18, 295],
 [2284,
  2127,
  2072,
  1607,
  4256,
  194,
  4934,
  4458,
  17,
  3986,
  4710,
  1082,
  4056,
  2647,
  2951,
  629,
  2080],
 [3287, 3411],
 [1285, 4256, 264, 4965, 2

# Embedding Representation

In [20]:
sent_length=15
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...    0 4924 2913]
 [   0    0    0 ... 4488 1603 4180]
 [   0    0    0 ... 3872  661 1683]
 ...
 [   0    0    0 ... 4002 2852 2754]
 [   0    0    0 ... 2961 2754  412]
 [   0    0    0 ...    0 2754 2320]]


In [21]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 4924, 2913])

In [22]:
## Creating model
embedding_vector_features=50
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 15, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [23]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.1))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 15, 50)            250000    
                                                                 
 bidirectional (Bidirection  (None, 200)               120800    
 al)                                                             
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 371001 (1.42 MB)
Trainable params: 371001 (1.42 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [24]:
len(embedded_docs),y.shape

(21459, (21459,))

In [25]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [26]:
X_final.shape,y_final.shape

((21459, 15), (21459,))

# Splitting the Dataset

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.1, random_state = 42)

# Training the model

In [28]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10)

Epoch 1/10
604/604 [==============================] - 11s 13ms/step - loss: -2.7377 - accuracy: 0.5853 - val_loss: -8.4048 - val_accuracy: 0.6393
Epoch 2/10
604/604 [==============================] - 7s 12ms/step - loss: -15.7249 - accuracy: 0.6691 - val_loss: -19.8007 - val_accuracy: 0.6459
Epoch 3/10
604/604 [==============================] - 7s 12ms/step - loss: -29.2759 - accuracy: 0.6874 - val_loss: -30.7875 - val_accuracy: 0.6500
Epoch 4/10
604/604 [==============================] - 7s 12ms/step - loss: -43.9600 - accuracy: 0.6886 - val_loss: -39.2406 - val_accuracy: 0.6412
Epoch 5/10
604/604 [==============================] - 7s 12ms/step - loss: -58.2602 - accuracy: 0.6909 - val_loss: -34.2146 - val_accuracy: 0.6086
Epoch 6/10
604/604 [==============================] - 7s 12ms/step - loss: -61.7250 - accuracy: 0.6724 - val_loss: -53.2136 - val_accuracy: 0.6361
Epoch 7/10
604/604 [==============================] - 7s 12ms/step - loss: -84.7924 - accuracy: 0.6862 - val_loss: -67.

In [29]:
X_test

array([[   0,    0,    0, ...,  824, 3775, 4578],
       [   0,    0,    0, ..., 1964, 1106, 1580],
       [   0,    0,    0, ...,  842, 1791, 2656],
       ...,
       [   0,    0, 1986, ..., 4861, 3431, 2341],
       [ 687, 1580, 1762, ..., 4861, 3431, 4513],
       [3389, 1120,  636, ..., 4491, 1468, 4405]])

In [30]:
y_pred1 = model1.predict(X_test)
y_pred_classes = (y_pred1 > 0.5).astype("int64")

68/68 [==============================] - 1s 4ms/step


In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_classes)

array([[740, 226,   0],
       [130, 690,   0],
       [ 19, 341,   0]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_classes)

0.6663560111835974

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_classes))

              precision    recall  f1-score   support

           0       0.83      0.77      0.80       966
           1       0.55      0.84      0.66       820
           2       0.00      0.00      0.00       360

    accuracy                           0.67      2146
   macro avg       0.46      0.54      0.49      2146
weighted avg       0.58      0.67      0.61      2146



C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\patil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
